// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: api/v1/settings/settings.proto

package settings

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ColorSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int64     `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pallets []*Pallet `protobuf:"bytes,2,rep,name=pallets,proto3" json:"pallets,omitempty"`
}

func (x *ColorSettings) Reset() {
	*x = ColorSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_settings_settings_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColorSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorSettings) ProtoMessage() {}

func (x *ColorSettings) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_settings_settings_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorSettings.ProtoReflect.Descriptor instead.
func (*ColorSettings) Descriptor() ([]byte, []int) {
	return file_api_v1_settings_settings_proto_rawDescGZIP(), []int{0}
}

func (x *ColorSettings) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ColorSettings) GetPallets() []*Pallet {
	if x != nil {
		return x.Pallets
	}
	return nil
}

type Pallet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Colors []*AltitudeColor `protobuf:"bytes,2,rep,name=colors,proto3" json:"colors,omitempty"`
}

func (x *Pallet) Reset() {
	*x = Pallet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_settings_settings_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pallet) ProtoMessage() {}

func (x *Pallet) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_settings_settings_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pallet.ProtoReflect.Descriptor instead.
func (*Pallet) Descriptor() ([]byte, []int) {
	return file_api_v1_settings_settings_proto_rawDescGZIP(), []int{1}
}

func (x *Pallet) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pallet) GetColors() []*AltitudeColor {
	if x != nil {
		return x.Colors
	}
	return nil
}

type AltitudeColor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Altitude float64 `protobuf:"fixed64,1,opt,name=altitude,proto3" json:"altitude,omitempty"`
	R        uint32  `protobuf:"varint,2,opt,name=r,proto3" json:"r,omitempty"`
	G        uint32  `protobuf:"varint,3,opt,name=g,proto3" json:"g,omitempty"`
	B        uint32  `protobuf:"varint,4,opt,name=b,proto3" json:"b,omitempty"`
	A        uint32  `protobuf:"varint,5,opt,name=a,proto3" json:"a,omitempty"`
}

func (x *AltitudeColor) Reset() {
	*x = AltitudeColor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_settings_settings_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AltitudeColor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AltitudeColor) ProtoMessage() {}

func (x *AltitudeColor) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_settings_settings_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AltitudeColor.ProtoReflect.Descriptor instead.
func (*AltitudeColor) Descriptor() ([]byte, []int) {
	return file_api_v1_settings_settings_proto_rawDescGZIP(), []int{2}
}

func (x *AltitudeColor) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *AltitudeColor) GetR() uint32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *AltitudeColor) GetG() uint32 {
	if x != nil {
		return x.G
	}
	return 0
}

func (x *AltitudeColor) GetB() uint32 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *AltitudeColor) GetA() uint32 {
	if x != nil {
		return x.A
	}
	return 0
}

type GetDefaultSettingsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDefaultSettingsRequest) Reset() {
	*x = GetDefaultSettingsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_settings_settings_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDefaultSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefaultSettingsRequest) ProtoMessage() {}

func (x *GetDefaultSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_settings_settings_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefaultSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetDefaultSettingsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_settings_settings_proto_rawDescGZIP(), []int{3}
}

type GetDefaultSettingsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pallet *Pallet `protobuf:"bytes,1,opt,name=pallet,proto3" json:"pallet,omitempty"`
}

func (x *GetDefaultSettingsResponse) Reset() {
	*x = GetDefaultSettingsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_settings_settings_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDefaultSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefaultSettingsResponse) ProtoMessage() {}

func (x *GetDefaultSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_settings_settings_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefaultSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetDefaultSettingsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_settings_settings_proto_rawDescGZIP(), []int{4}
}

func (x *GetDefaultSettingsResponse) GetPallet() *Pallet {
	if x != nil {
		return x.Pallet
	}
	return nil
}

type GetSettingsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetSettingsRequest) Reset() {
	*x = GetSettingsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_settings_settings_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsRequest) ProtoMessage() {}

func (x *GetSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_settings_settings_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetSettingsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_settings_settings_proto_rawDescGZIP(), []int{5}
}

func (x *GetSettingsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetSettingsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Settings *ColorSettings `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
}

func (x *GetSettingsResponse) Reset() {
	*x = GetSettingsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_settings_settings_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsResponse) ProtoMessage() {}

func (x *GetSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_settings_settings_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetSettingsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_settings_settings_proto_rawDescGZIP(), []int{6}
}

func (x *GetSettingsResponse) GetSettings() *ColorSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

var File_api_v1_settings_settings_proto protoreflect.FileDescriptor

var file_api_v1_settings_settings_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x2f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1c, 0x6f, 0x70, 0x65, 0x6e, 0x70, 0x67, 0x6c, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x68,
	0x0a, 0x0d, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x3e, 0x0a, 0x07, 0x70, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6f, 0x70, 0x65, 0x6e,
	0x70, 0x67, 0x6c, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x50, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52,
	0x07, 0x70, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x73, 0x22, 0x5d, 0x0a, 0x06, 0x50, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x43, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x70, 0x67, 0x6c, 0x2e, 0x73, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x2e, 0x41, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52,
	0x06, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x73, 0x22, 0x63, 0x0a, 0x0d, 0x41, 0x6c, 0x74, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x6c, 0x74, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x61, 0x6c, 0x74, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x01, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x67,
	0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x62, 0x12, 0x0c,
	0x0a, 0x01, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x61, 0x22, 0x1b, 0x0a, 0x19,
	0x47, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5a, 0x0a, 0x1a, 0x47, 0x65, 0x74,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x06, 0x70, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x70, 0x67,
	0x6c, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x50, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x06, 0x70,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x22, 0x2d, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x5e, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x08, 0x73,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e,
	0x6f, 0x70, 0x65, 0x6e, 0x70, 0x67, 0x6c, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x43, 0x6f, 0x6c,
	0x6f, 0x72, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x08, 0x73, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x32, 0x93, 0x02, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x89, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12,
	0x37, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x70, 0x67, 0x6c, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x47,
	0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x38, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x70,
	0x67, 0x6c, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x73,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x74, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x12, 0x30, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x70, 0x67, 0x6c, 0x2e, 0x73, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x70, 0x67, 0x6c, 0x2e,
	0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x4d, 0x5a, 0x4b, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x65, 0x74, 0x6d, 0x6f, 0x72,
	0x72, 0x6f, 0x77, 0x73, 0x6f, 0x6c, 0x6f, 0x6e, 0x6d, 0x61, 0x72, 0x73, 0x2f, 0x6f, 0x70, 0x65,
	0x6e, 0x70, 0x67, 0x6c, 0x2f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31,
	0x2f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_v1_settings_settings_proto_rawDescOnce sync.Once
	file_api_v1_settings_settings_proto_rawDescData = file_api_v1_settings_settings_proto_rawDesc
)

func file_api_v1_settings_settings_proto_rawDescGZIP() []byte {
	file_api_v1_settings_settings_proto_rawDescOnce.Do(func() {
		file_api_v1_settings_settings_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_settings_settings_proto_rawDescData)
	})
	return file_api_v1_settings_settings_proto_rawDescData
}

var file_api_v1_settings_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_v1_settings_settings_proto_goTypes = []interface{}{
	(*ColorSettings)(nil),              // 0: openpgl.settings.v1.settings.ColorSettings
	(*Pallet)(nil),                     // 1: openpgl.settings.v1.settings.Pallet
	(*AltitudeColor)(nil),              // 2: openpgl.settings.v1.settings.AltitudeColor
	(*GetDefaultSettingsRequest)(nil),  // 3: openpgl.settings.v1.settings.GetDefaultSettingsRequest
	(*GetDefaultSettingsResponse)(nil), // 4: openpgl.settings.v1.settings.GetDefaultSettingsResponse
	(*GetSettingsRequest)(nil),         // 5: openpgl.settings.v1.settings.GetSettingsRequest
	(*GetSettingsResponse)(nil),        // 6: openpgl.settings.v1.settings.GetSettingsResponse
}
var file_api_v1_settings_settings_proto_depIdxs = []int32{
	1, // 0: openpgl.settings.v1.settings.ColorSettings.pallets:type_name -> openpgl.settings.v1.settings.Pallet
	2, // 1: openpgl.settings.v1.settings.Pallet.colors:type_name -> openpgl.settings.v1.settings.AltitudeColor
	1, // 2: openpgl.settings.v1.settings.GetDefaultSettingsResponse.pallet:type_name -> openpgl.settings.v1.settings.Pallet
	0, // 3: openpgl.settings.v1.settings.GetSettingsResponse.settings:type_name -> openpgl.settings.v1.settings.ColorSettings
	3, // 4: openpgl.settings.v1.settings.SettingsService.GetDefaultSettings:input_type -> openpgl.settings.v1.settings.GetDefaultSettingsRequest
	5, // 5: openpgl.settings.v1.settings.SettingsService.GetSettings:input_type -> openpgl.settings.v1.settings.GetSettingsRequest
	4, // 6: openpgl.settings.v1.settings.SettingsService.GetDefaultSettings:output_type -> openpgl.settings.v1.settings.GetDefaultSettingsResponse
	6, // 7: openpgl.settings.v1.settings.SettingsService.GetSettings:output_type -> openpgl.settings.v1.settings.GetSettingsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_v1_settings_settings_proto_init() }
func file_api_v1_settings_settings_proto_init() {
	if File_api_v1_settings_settings_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_settings_settings_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColorSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_settings_settings_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pallet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_settings_settings_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AltitudeColor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_settings_settings_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDefaultSettingsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_settings_settings_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDefaultSettingsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_settings_settings_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSettingsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_settings_settings_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSettingsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_settings_settings_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_settings_settings_proto_goTypes,
		DependencyIndexes: file_api_v1_settings_settings_proto_depIdxs,
		MessageInfos:      file_api_v1_settings_settings_proto_msgTypes,
	}.Build()
	File_api_v1_settings_settings_proto = out.File
	file_api_v1_settings_settings_proto_rawDesc = nil
	file_api_v1_settings_settings_proto_goTypes = nil
	file_api_v1_settings_settings_proto_depIdxs = nil
}
